=== Dusevna1994/NRT_94_14/oglasi.dtd
<!ELEMENT oglasiLista (oglas*)>
<!ELEMENT oglas (kategorija,datumIsteka,cena,tekst,oznaka*,email+)>
<!ELEMENT kategorija (#PCDATA)>
<!ELEMENT datumIsteka (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekst (#PCDATA)>
<!ELEMENT oznaka (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ATTLIST oglasiLista xsi:schemaLocation CDATA #REQUIRED
		      xmlns CDATA #REQUIRED
		      xmlns:xsi CDATA #REQUIRED>
<!ATTLIST cena valuta (rsd|eur) "rsd">
<!ATTLIST email tip (privatni|sluzbeni) #REQUIRED>

=== Dusevna1994/NRT_94_14/oglasi.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE oglasiLista SYSTEM "oglasi.dtd">
<oglasiLista>
	<oglas>
		<kategorija></kategorija>
		<datumIsteka></datumIsteka>
		<cena valuta="eur"></cena>
		<tekst></tekst>
		<oznaka></oznaka>
		<email tip="privatni"></email>
	</oglas>
	<oglas>
		<kategorija></kategorija>
		<datumIsteka></datumIsteka>
		<cena valuta="rsd"></cena>
		<tekst></tekst>
		<oznaka></oznaka>
		<email tip="privatni"></email>
	</oglas>
	<oglas>
		<kategorija></kategorija>
		<datumIsteka></datumIsteka>
		<cena valuta="rsd"></cena>
		<tekst></tekst>
		<oznaka></oznaka>
		<email tip="sluzbeni"></email>
	</oglas>
</oglasiLista>
